### ISSUE TITLE
2.0 roadmap

### ISSUE THREAD

**Issue by lgg** [lgg/vk-to-telegram-bot#38]
## Common
- [ ] test 
- [ ] 
- [ ] 
- [ ] 

## VK Parsing
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Telegram API
- [ ] Post editing(manually and auto) - check if VK Post Changed - update Telegram Text
- [ ] Ability to delete message if it deleted from VK
- [ ] 
- [ ] 

## Docs
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Other
- [ ] cli tool for manually parsing VK and posting to Telegram(with and w/o writing to DB) + manually repost from VK to Telegram by url
- [ ] ability to sync all VK posts to Telegram
- [ ] ability to clear BD for specific post
- [ ] 
- [ ]
